// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAha4z0lziZOGx0mf7aIjN8s84kseNSuVM',
    appId: '1:870314332331:web:bd0aa420250b2f41aee7ee',
    messagingSenderId: '870314332331',
    projectId: 'chat-app-a7b79',
    authDomain: 'chat-app-a7b79.firebaseapp.com',
    storageBucket: 'chat-app-a7b79.firebasestorage.app',
    measurementId: 'G-R4XYF9DHBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeOe6vBjL1sbYT-sRFjtLLyxk9tIXOwY',
    appId: '1:870314332331:android:045872d5d9acfe7daee7ee',
    messagingSenderId: '870314332331',
    projectId: 'chat-app-a7b79',
    storageBucket: 'chat-app-a7b79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaI_UBWi9kAMomhv5KCJK8sVfhUMNZh04',
    appId: '1:870314332331:ios:4a79dd13c381f5f7aee7ee',
    messagingSenderId: '870314332331',
    projectId: 'chat-app-a7b79',
    storageBucket: 'chat-app-a7b79.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaI_UBWi9kAMomhv5KCJK8sVfhUMNZh04',
    appId: '1:870314332331:ios:4a79dd13c381f5f7aee7ee',
    messagingSenderId: '870314332331',
    projectId: 'chat-app-a7b79',
    storageBucket: 'chat-app-a7b79.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAha4z0lziZOGx0mf7aIjN8s84kseNSuVM',
    appId: '1:870314332331:web:4ab954442317fbc3aee7ee',
    messagingSenderId: '870314332331',
    projectId: 'chat-app-a7b79',
    authDomain: 'chat-app-a7b79.firebaseapp.com',
    storageBucket: 'chat-app-a7b79.firebasestorage.app',
    measurementId: 'G-WX9H3ZS6RM',
  );

}